language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"

# command to install dependencies.
install: true
  # - pip install -r requirements.txt

# command to build and run tests.
script:
  - python setup.py build test sdist
